"use client";
import { FormEvent, useEffect, useState } from "react";
import { adminFetch, readSession, Session } from "../components/admin-client";
type Admin = { username: string; is_root: boolean; disabled: boolean };
export default function AdministratorsPage() { const [session, setSession] = useState<Session | null>(null); const [accounts, setAccounts] = useState<Admin[]>([]); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState("");
  async function load(current = session) { if (!current) return; const r = await adminFetch("/api/admin/accounts", current); if (r.ok) setAccounts(await r.json()); }
  useEffect(() => { const current = readSession(); setSession(current); if (current) load(current); }, []);
  async function create(event: FormEvent) { event.preventDefault(); if (!session) return; const r = await adminFetch("/api/admin/accounts", session, { method: "POST", headers: { "Target-Username": username, "New-Password": password } }); setMessage(r.ok ? "Administrator created." : "Could not create administrator."); if (r.ok) { setUsername(""); setPassword(""); load(); } }
  async function toggle(account: Admin) { if (!session || account.is_root) return; const r = await adminFetch(`/api/admin/accounts/${encodeURIComponent(account.username)}?disabled=${!account.disabled}`, session, { method: "PATCH" }); setMessage(r.ok ? "Administrator updated." : "Could not update administrator."); load(); }
  return <div><p className="text-sm text-violet-200/70">Access control</p><h1 className="mt-2 text-4xl font-black">Administrators</h1><div className="mt-8 grid gap-6 lg:grid-cols-[1.4fr_1fr]"><section className="overflow-hidden rounded-2xl border border-white/10 bg-black/25 backdrop-blur-xl"><div className="border-b border-white/10 px-5 py-4 text-xs font-bold uppercase tracking-wider text-white/40">Local administrators</div>{accounts.map(account => <div key={account.username} className="flex items-center justify-between border-b border-white/5 px-5 py-4 last:border-0"><div><p className="font-semibold">{account.username}</p><p className="mt-1 text-xs text-white/40">{account.is_root ? "Root administrator" : account.disabled ? "Disabled" : "Administrator"}</p></div>{!account.is_root && <button onClick={() => toggle(account)} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-white/65 hover:bg-white/10">{account.disabled ? "Enable" : "Disable"}</button>}</div>)}</section><form onSubmit={create} className="rounded-2xl border border-white/10 bg-black/25 p-6 backdrop-blur-xl"><h2 className="text-lg font-semibold">Add administrator</h2><p className="mt-2 text-sm text-white/45">Create a local console account.</p><input required value={username} onChange={e => setUsername(e.target.value)} placeholder="Username" className="mt-5 h-11 w-full rounded-xl border border-white/10 bg-white/5 px-4 text-sm outline-none placeholder:text-white/30" /><input required minLength={8} type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Password (8+ characters)" className="mt-3 h-11 w-full rounded-xl border border-white/10 bg-white/5 px-4 text-sm outline-none placeholder:text-white/30" /><button className="mt-4 rounded-xl bg-violet-300 px-4 py-3 text-sm font-semibold text-black">Create administrator</button>{message && <p className="mt-4 text-sm text-violet-200">{message}</p>}</form></div></div>; }
