"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { adminFetch, readSession, Session } from "./components/admin-client";

type Overview = { users: number; active_users: number; disabled_users: number; administrators: number; pending_invites: number };
export default function DashboardOverview() {
  const [session, setSession] = useState<Session | null>(null); const [data, setData] = useState<Overview | null>(null);
  useEffect(() => { const current = readSession(); if (current) { setSession(current); adminFetch("/api/admin/overview", current).then(r => r.ok && r.json()).then(value => value && setData(value)); } }, []);
  const stats = data ? [["Users", data.users, "/web/dashboard/users"], ["Active users", data.active_users, "/web/dashboard/users"], ["Administrators", data.administrators, "/web/dashboard/administrators"], ["Pending invites", data.pending_invites, "/web/dashboard/invites"]] : [];
  return <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm text-violet-200/70">Overview</p><h1 className="mt-2 text-4xl font-black tracking-tight">Good to see you, {session?.username}</h1><p className="mt-3 text-sm text-white/45">Manage your ZenStream service from one place.</p></div><Link href="/web/dashboard/users" className="rounded-xl bg-violet-300 px-4 py-3 text-center text-sm font-semibold text-black">Manage users</Link></div><section className="mt-10 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([label, value, href]) => <Link href={String(href)} key={String(label)} className="rounded-2xl border border-white/10 bg-black/25 p-5 backdrop-blur-xl transition hover:border-violet-300/50 hover:bg-white/[.06]"><p className="text-sm text-white/45">{label}</p><p className="mt-4 text-4xl font-black">{value}</p><p className="mt-3 text-xs font-semibold uppercase tracking-wider text-violet-200/70">View details →</p></Link>)}</section><section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-black/25 p-6 backdrop-blur-xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-violet-300">Quick actions</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><Link href="/web/dashboard/invites" className="rounded-xl border border-white/10 bg-white/[.03] p-4 text-sm hover:bg-white/10">Generate invite</Link><Link href="/web/dashboard/administrators" className="rounded-xl border border-white/10 bg-white/[.03] p-4 text-sm hover:bg-white/10">Manage administrators</Link><Link href="/web/dashboard/profile" className="rounded-xl border border-white/10 bg-white/[.03] p-4 text-sm hover:bg-white/10">Update profile</Link></div></div><div className="rounded-2xl border border-white/10 bg-black/25 p-6 backdrop-blur-xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-violet-300">System status</p><p className="mt-5 text-lg font-semibold">Orchestrator online</p><p className="mt-2 text-sm text-white/45">Administrative controls are protected by local orchestrator authentication.</p></div></section></div>;
}
