"""Discard pending roots created by the pre-0017 broken ledger."""

import sqlalchemy as sa
from alembic import op

revision = "0018_library_watch_pending_cleanup"
down_revision = "0017_library_watch_ledger_repair"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    tables = set(sa.inspect(bind).get_table_names())
    if "library_watch_pending_roots" in tables:
        # The repaired directory ledger and next delta cycle provide a fresh,
        # safe source of truth. These rows were generated by the old probe and
        # can otherwise replay hundreds of unrelated roots after restart.
        bind.execute(sa.text("DELETE FROM library_watch_pending_roots"))


def downgrade() -> None:
    raise NotImplementedError()
